Fix reno release naming and dvsm functional job
This change contains two changes to fix our CI:
- a reno branch naming issue
- a permission issue in devstack VM functional job

On the reno branch naming issue: something must have
changed somewhere in the way we should name branches
in reno files (old way: origin/stable/newton
new: stable/newton).

...
    ldr = loader.Loader(conf)
  File "/home/teom7365/prog/openstack/networking-bgpvpn/.tox/releasenotes/local/lib/python2.7/site-packages/reno/loader.py", line 60, in __init__
    self._load_data()
  File "/home/teom7365/prog/openstack/networking-bgpvpn/.tox/releasenotes/local/lib/python2.7/site-packages/reno/loader.py", line 80, in _load_data
    self._scanner_output = self._scanner.get_notes_by_version()
  File "/home/teom7365/prog/openstack/networking-bgpvpn/.tox/releasenotes/local/lib/python2.7/site-packages/reno/scanner.py", line 577, in get_notes_by_version
    versions_by_date = self._get_tags_on_branch(branch)
  File "/home/teom7365/prog/openstack/networking-bgpvpn/.tox/releasenotes/local/lib/python2.7/site-packages/reno/scanner.py", line 344, in _get_tags_on_branch
    for c in self._get_walker_for_branch(branch):
  File "/home/teom7365/prog/openstack/networking-bgpvpn/.tox/releasenotes/local/lib/python2.7/site-packages/reno/scanner.py", line 338, in _get_walker_for_branch
    branch_head = self._get_ref(branch)
  File "/home/teom7365/prog/openstack/networking-bgpvpn/.tox/releasenotes/local/lib/python2.7/site-packages/reno/scanner.py", line 334, in _get_ref
    raise ValueError('Unknown reference {!r}'.format(name))
ValueError: Unknown reference 'origin/stable/newton'

Change-Id: I22c09534bc713f4eb00d106285a07acdd6e99730