Fix recent gate failures
* pep8 execution failed on pylint phase with some astroid traceback for
  RuntimeError: generator raised StopIteration.
  The issue can be solved by setting both pylint and astroid versions.
  The new pylint causes some new checks, like inheriting from object which
  in py3 is not necessary again to write out.

* Fix some db shcema mismatches between migration scripts and model.

* Bump the lower bound of pyScss which is a dependency of horizon
  to 1.3.7 to make it work with setuptools 46. This just follows
  horizon change https://review.opendev.org/#/c/715241/.

Change-Id: I4119f6455e7af83cf397dec531b0a11f88112f21